config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "static_pages#home"
  resources :tweets, except: [:update, :edit]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/hashtag.rb
class Hashtag < ApplicationRecord
    has_many :tags 

    validates :name, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord 
    belongs_to :hashtag
    belongs_to :tweet
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    belongs_to :user
    has_many :tags
    attribute :hashtags

    after_create :create_tags

    def create_tags
        hashtags.split(',').each do |h|
            hashtag = Hashtag.find_or_create_by name: h
            Tag.create tweet: self, hashtag: hashtag
        end
    end   

    def creation_date 
        created_at.strftime("%e %b %Y")
    end 

    def list_hashtags 
        tags.map{ |t| t.hashtag.name }.join(',')
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name, presence: true
  validates :last_name, presence: true

  has_many :tweets
  
  def full_name 
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    def home
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController 
    def index 
        @tweets = Tweet.all
    end

    def show 
        @tweet = Tweet.find(params[:id])
    end

    def new
        @tweet = Tweet.new
    end

    def create 
        tweet = Tweet.new tweet_params
        tweet.user = current_user
        if tweet.save
            redirect_to tweet, notice: 'Tweet guardado con éxito'
        else 
            render :new
        end
    end    

    def destroy 
        tweet = Tweet.find(params[:id])
        tweet.destroy
        redirect_to tweets_path, notice: 'Tweet eliminado con éxito'
    end

    private 
    def tweet_params 
        params.require(:tweet).permit(:body, :hashtags)
    end
end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_flash.html.erb
<% if notice %>
    <div class="alert alert-success" role="alert">
        <%= notice %>
    </div>
<% end %>
<% if alert %>
    <div class="alert alert-danger" role="alert">
        <%= alert %>
    </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to 'sTwiter', root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Home', root_path, class:'nav-link active' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Tweet', tweets_path, class:'nav-link active' %>
        </li>
        <li class='nav-item'>
            <%= link_to 'Crear', new_tweet_path, class:'nav-link active' %>
          </li>
        <% if user_signed_in?%>
          <li class='nav-item'>
            <%= button_to 'Salir', destroy_user_session_path, method: :delete, class:'nav-link' %>
          </li>
        <% end %>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success mt-2" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleTwiter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render partial: 'layouts/navbar' %>
    <%= render partial: 'layouts/flash' %>
    <%= yield %>
  </body>
</html>

app/views/static_pages/home.html.erb
<h1>home</h1>

app/views/tweets/_tweet.html.erb
<div class="card">
  <div class="card-header">
    <%= tweet.user.full_name %>
  </div>
  <div class="card-body">
    <blockquote class="blockquote mb-0">
      <p><%= tweet.body %></p>
      <footer class="blockquote-footer"><%= tweet.creation_date %></footer>
      <footer class="blockquote-footer"><%= tweet.list_hashtags %></footer>
      <%= link_to 'Ver', tweet, class:'btn btn-primary mt-2' %>
      <%= button_to 'Eliminar', tweet_path(tweet), method: :delete, class:'btn btn-danger mt-2' %>
    </blockquote>
  </div>
</div>

app/views/tweets/index.html.erb
<div class='container'>
<h1>Timeline</h1>
    <%= render partial: 'tweet', collection: @tweets %>
</div>

app/views/tweets/new.html.erb
<div class='container'>
    <h1> Nuevo tweet</h1>
    <%= form_with model: @tweet do |f| %>
        <div class='form-row'>
            <div class='form-group col-6'>
                <%= f.text_field :body, placeholder: 'comparte tu estado', class:'form-control' %>
            </div>
            <br/>
            <div class="form-group col-6">
                <%= f.text_field :hashtags, placeholder: 'Hashtags', class: 'form-control' %>
            </div>
        </div>
        <%= f.submit 'Guardar', class:'btn btn-primary mt-2' %>
    <% end %>
</div>

app/views/tweets/show.html.erb
<div class='container'>
    <h1>Tweet details</h1>
    <%= render partial: 'tweet', locals: {tweet: @tweet} %>
</div>